sonar.projectKey=HimajaJutur_Salonsync
sonar.organization=himajajutur
sonar.projectName=Salonsync
sonar.sources=.
sonar.python.coverage.reportPaths=coverage.xml

# Exclude backend system files from coverage
sonar.coverage.exclusions=salonsync/settings.py,salon/utils.py,salon/templatetags/convert.py,**/migrations/**,**/tests/**