# Generated by Django 5.2.7 on 2025-11-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="selected_services",
            field=models.TextField(
                blank=True,
                help_text="Stores selected service names and details in JSON format",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="total_cost",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="appointment",
            name="total_minutes",
            field=models.IntegerField(default=0),
        ),
    ]
