# Generated by Django 5.2.7 on 2025-11-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0002_appointment_selected_services_appointment_total_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
