# Generated by Django 5.2.7 on 2025-11-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0003_appointment_cancelled_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="selected_services",
            field=models.TextField(blank=True),
        ),
    ]
