# Generated by Django 5.2.7 on 2025-11-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0004_alter_appointment_selected_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="coupon_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="discount_given",
            field=models.IntegerField(default=0),
        ),
    ]
