# Generated by Django 5.2.7 on 2025-11-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0005_appointment_coupon_code_appointment_discount_given"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("FLAT", "Flat Amount (Euro)"),
                            ("PERCENT", "Percentage (%)"),
                        ],
                        default="FLAT",
                        max_length=10,
                    ),
                ),
                ("amount", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
