# Generated by Django 5.2.7 on 2025-11-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0006_coupon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="description",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="discount_type",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="expiry_date",
        ),
        migrations.AddField(
            model_name="coupon",
            name="discount",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coupon",
            name="minimum_amount",
            field=models.IntegerField(default=0),
        ),
    ]
