# Generated by Django 5.2.7 on 2025-11-20 03:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0008_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="created_at",
        ),
        migrations.AddField(
            model_name="payment",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="payment",
            name="appointment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="salon.appointment"
            ),
        ),
    ]
