# Generated by Django 5.2.7 on 2025-11-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0009_remove_payment_created_at_payment_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("QR", "QR Payment"),
                    ("CARD", "Credit/Debit Card"),
                    ("CASH", "Cash at Salon"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
